# Production values for kafka-connect-ui.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: landoop/kafka-connect-ui
  tag: 0.9.7
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80
  annotations: {}
  ## Limit load balancer source ips to list of CIDRs (where available)
  # loadBalancerSourceRanges: []

kafkaConnect:
  url: "http://localhost"
  port: 8083
  proxy: false
  allowGlobal: false
  allowTransitive: false
  allowDeletion: false
  readOnlyMode: false

ingress:
  enabled: false
  annotations: {}
  path: /
  hosts:
    - kafka-connect-ui.local
  tls: []

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
