apiVersion: v1
kind: Service
metadata:
  name: {{ template "kafka-connect-ui.fullname" . }}
  labels:
    app: {{ template "kafka-connect-ui.name" . }}
    chart: {{ template "kafka-connect-ui.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- range $key, $value := . }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
spec:
  {{- if .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- range $cidr := .Values.service.loadBalancerSourceRanges }}
    - {{ $cidr }}
    {{- end }}
  {{- end }}
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ template "kafka-connect-ui.name" . }}
    release: {{ .Release.Name }}
